### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by reinzor** [ros-drivers/odva_ethernetip#10]
Can somebody release the package so we can update the omron drivers with the local_ip functionality?

**Comment by mikepurvis** [comment]
Done:

Indigo: ros/rosdistro#17426

Kinetic: ros/rosdistro#17427

Melodic appears to be having build issues due to the newer/stricter compiler, so I've put up a PR to withdraw that one: https://github.com/ros/rosdistro/pull/17468
